### ISSUE TITLE
Assignment of more than one advocate to the same appointment

### ISSUE THREAD

**Issue by kneerunjun** [CrackDataPots/legallyright#14]
can one appointment be handled by 2 of the firm's own advocates ? so if the petitioner is the client for Advocate A and respondent is the client for Advocate B , both A & B being the employees of the same firm ?

**Comment by kneerunjun** [comment]
join to issue #2

**Comment by siddhesh-athalekar** [comment]
Have sent the question to the client. Awaiting response.

**Comment by siddhesh-athalekar** [comment]
Response : "Nope. As the appearance is filed by the firm, we can't file for plaintiff and defendant at the same time. That is conflict of interest."

**Comment by kneerunjun** [comment]
ok ! , closing this
